# from https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Publish .NET Core Project
      run: dotnet publish Sz.Timeline/Server/Sz.Timeline.Server.csproj -c Release -o release --nologo    
    - name: Change base-tag in index.html from / to Timeline
      run: sed -i 's/<base href="\/" \/>/<base href="\/Timeline\/" \/>/g' release/wwwroot/index.html
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
